-- Database exploration
select * from INFORMATION_SCHEMA.TABLES
select * from INFORMATION_SCHEMA.COLUMNS
-- Columns exploration
where TABLE_NAME = 'dim_customers'
select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'dim_products'
select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'fact_sales'
--Dimension exploration
select DISTINCT country
from dim_customers

select DISTINCT category, subcategory
from dim_products

-- Date exploration
--Timespan in dataset
Select MIN(order_date) as First_order_date,
MAX(Order_date) as last_order_date,
DATEDIFF(YEAR, MIN(order_date), MAX(Order_date)) AS No_of_years
from fact_sales

--Youngest and oldest customer 
select MIN(birthdate) AS oldest_customer,
DATEDIFF (year, MIN(birthdate), getdate()) AS OLDEST_AGE,
MAX(birthdate) AS YOUNGEST_AGE,
DATEDIFF (year, MAX(birthdate), getdate()) AS YOUNGEST_AGE
from dim_customers

--Measure exploration
--Find the total sales
select SUM(Sales_amount) AS Total_sales 
from fact_sales

--How many items are sold?
select SUM(quantity) AS Total_quantity
from fact_sales

--Find the average selling price
Select AVG(price) AS AVG_price
from fact_sales

--Find the total number of orders
select count(order_number) AS Total_orders
from fact_sales
select count(DISTINCT order_number) AS Total_orders
from fact_sales

--Find the total number of customers
select count(DISTINCT customer_id) AS Total_customers
from dim_customers

--Find the total number of products
Select count(DISTINCT product_id) AS Total_products
from dim_products

--Find the total number of customers that have placed an order
Select COUNT(customer_id)
from dim_customers

--Generate a report that shows all key metrics of the business
select 'TOTAL_SALES' AS Measure_name,SUM(Sales_amount) AS Measure_value from fact_sales
UNION ALL
select 'TOTAL_QUANTITY' AS Measure_name,SUM(quantity) AS Measure_value from fact_sales
UNION ALL
Select 'AVERAGE_PRICE' AS measure_name, AVG(price) AS Measure_value from fact_sales
UNION ALL
select 'Total_orders' AS measure_name,count(DISTINCT order_number) AS measure_value from fact_sales
UNION ALL
select 'total_customers' as measure_nmae, count(DISTINCT customer_id) AS MEASURE_VALUE from dim_customers
UNION ALL
Select 'Total_products' as measure_name,count(DISTINCT product_id) AS measure_value from dim_products

--MAGNITUDE ANALYSIS
--Find total customers by countries
select COUNTRY,
COUNT(DISTINCT customer_id) AS Total_customers
from dim_customers
group by Country
ORDER BY TOTAL_CUSTOMERS DESC

--Find the total customers by gender
Select Gender,
COUNT(DISTINCT customer_id) AS Total_customers
from dim_customers
group by gender
ORDER BY TOTAL_CUSTOMERS DESC

--Find the total_products by category
select Category, 
count(product_id) AS TOTAL_Products
from dim_products
group by category
order by Total_products DESC

--Find the average cost in each category
Select category,
avg(cost) AS Average_cost
from dim_products
group by category
order by Average_cost DESC

--Find the total revenue generated in each category
Select p.category,
SUM(s.sales_amount) AS Total_revenue
from fact_sales as s
left join dim_products as p
on p.product_key = s.product_key
group by p.category
order by Total_revenue DESC


--find the total revenue generated by each customer
Select DISTINCT p.customer_key,
P.FIRST_NAME,
P.LAST_NAME,
SUM(s.sales_amount) AS Total_revenue
from fact_sales as s
left join dim_customers as p
on p.customer_key = s.customer_key
group by p.customer_key,
P.FIRST_NAME,
P.LAST_NAME
order by Total_revenue DESC

--Find the total distribution of sold items across countries
select c.country,
Count(s.quantity) AS Total_Quantity
from fact_sales as s
left join dim_customers as c
on s.Customer_key = c.customer_key
group by c.country
order by Total_Quantity DESC

--Ranking Analysis
--What 5 products generate the highest revenue?
select TOP 5
P.product_name,
SUM(S.sales_amount) as Highest_revenue
from dim_products as p
left join fact_sales as s
on P.product_key = s.product_key
group by p.product_name
ORDER BY Highest_revenue desc

--What are the 5 worst performing products in terms of sales?
select TOP 5
P.product_name,
SUM(S.sales_amount) as Highest_revenue
from fact_sales as s
left join dim_products as p
on P.product_key = s.product_key
group by p.product_name
ORDER BY Highest_revenue 

--Change over time
--Analyze sales performance over time
USE Data_warehouse_analytics
select
Year(order_date) AS Year,
Month(order_date) AS Month,
sum(sales_amount) as TOTAL_SALES,
Count(DISTINCT customer_key) AS Total_Customers,
SUM(Quantity) AS Total_Quantity
from fact_sales
where order_date is not null
Group by Year(order_date), Month(order_date)
order by Year(order_date), Month(order_date) DESC

--Cumulative Analysis
--Calculate the total sales of the month and the running sales over time 
SELECT 
ORDER_DATE,
TOTAL_SALES,
SUM(Total_sales) OVER (Partition by Order_date ORDER BY Order_date) AS Running_total_sales,
AVG(Total_sales) OVER (Order by order_date) AS Running_total_average
From 
(
Select 
DATETRUNC(month, order_date) AS Order_date,
SUM(sales_amount) AS Total_sales
from fact_sales
where Order_date IS NOT NULL
group by DATETRUNC(month, order_date)
)t

--Performance Analysis
--Analyze the yearly performance of products by comparing their sales to both the average sales performance of the product and the previous years sales
;WITH Yearly_performance AS (
Select 
Year(s.Order_date) AS Order_year,
p.product_name,
SUM(s.sales_amount) Total_sales
from fact_sales as s
left join dim_products as p
on p.product_key = s.product_key
Where s.order_date IS NOT NULL
Group by Year(s.Order_date), p.product_name
)

Select 
Order_year,
Product_name,
Total_sales,
AVG(Total_sales) Over(Partition by Product_name) AVG_sales,
Total_sales - AVG(Total_sales) Over(Partition by Product_name) AS Diff_avg,
Case when Total_sales - AVG(Total_sales) Over(Partition by Product_name) > 0 Then 'ABOVE AVG'
when Total_sales - AVG(Total_sales) Over(Partition by Product_name) < 0 Then 'Below avg'
ELSE 'AVG'
END AVG_change,
LAG(Total_sales) OVER( partition by product_name order by order_year) AS previous_year_sales,
Total_sales - LAG(Total_sales) OVER( partition by product_name order by order_year) AS Diff_py,
CASE WHEN Total_sales - LAG(Total_sales) OVER( partition by product_name order by order_year) > 0 THEN 'Increase'
WHEN Total_sales - LAG(Total_sales) OVER( partition by product_name order by order_year) < 0 Then 'Decrease'
else 'No change'
End Diff_sales_py
from Yearly_performance

USE Data_warehouse_analytics
--Part-to-whole analysis
--which category contribute most to the overall sales?
WITH Category_sales AS (
select 
p.category,
SUM(s.sales_amount) AS total_sales
from fact_sales as s
left join dim_products as p
on s.product_key = p.product_key
Group by Category)

Select 
category,
Total_sales,
SUM(Total_sales) over () AS Overall_sales,
Concat(ROUND((Cast(Total_sales AS float) / SUM(Total_sales) over ())*100, 2), '%') AS Percentage
from Category_sales
Order by Total_sales DESC

--Data segmentation
--Segment products into cost ranges and count how many products fall into each segment
WITH data_segmentation as (
select 
product_key,
product_name,
cost,
Case when cost < 100 then 'below 100'
when cost between 100 and 500 then '100-500'
when cost between 500 and 1000 then '500-1000'
else 'above 1000'
END cost_range
from dim_products)

select 
cost_range,
Count(product_key) as total_products
from data_segmentation
group by cost_range 
order by cost_range desc

--Group customers based on their spending behaviour :
-- Vip customers with at least 12 months of history and spending more than 5000
-- Regular customers with at least 12 months of history and spending less than 5000 
-- new customers with less than 12 months of history 
--And find the total number of customers by each group
WITH Data_segments as (
Select
c.customer_key,
SUM(s.sales_amount) AS Total_sp,
Min(s.order_date) AS First_order,
MAX(s.Order_date) AS Last_order,
DATEDIFF(month, Min(s.order_date), MAX(s.Order_date)) AS Lifespan
from fact_sales as s
left join dim_customers as c
ON s.customer_key = c.customer_key
group by c.customer_key)

select
case_segments,
count(customer_key) AS Total_customers
from (
Select
Customer_key,
Total_sp,
Case when Lifespan >= 12 and Total_sp >= 5000 then 'VIP'
when lifespan >= 12 and Total_sp <= 5000 then 'regular'
else 'NEW'
end Case_segments
from Data_segments)t
group by Case_segments
order by Total_customers DESC

--Build customers report
--Customer Report :
--Purpose : 
  ----This report consolidates key customer metrics and behaviour

  --Highlights :
  --1. Gather essential feilds such as names , ages and transaction details
  --2. segments customers into categories (VIP, Regular, New) and age groups
  --3. Aggregate customer-level metrics:
  ---Total orders
  ---Total sales
  ---Total quantity purchased
  ---Total products
  ---Lifespan (in months)
  --4. Calculate valuable KPIs
  ---recency (months since last order)
  ---average order value
  ---average monthly spend

  CREATE VIEW dbo.Customers_report AS
  WITH Base_query AS (
  --1. Base query : Retrives the core columns from tables
 Select
  f.order_number,
  f.product_key,
  F.order_date,
  f.sales_amount,
  f.quantity,
  c.customer_key,
  c.customer_number,
  Concat(c.first_name,' ',c.last_name) AS Customer_name,
  c.birthdate,
  DATEDIFF(year, c.birthdate, GETDATE()) AS Age
  FROM fact_sales as f
  left join dim_customers as c
  on f.customer_key = c.customer_key
  Where f.order_date is not null)

  --Customer aggregation : summarizes key metrics at the customer-level
  , Customer_aggregation AS (
  Select 
  customer_key,
  customer_number,
  customer_name,
  age,
  count(distinct order_number) AS Total_orders,
  SUM(sales_amount) AS Total_sales,
  SUM(quantity ) AS Total_quantity,
  Count(DISTINCT Product_key) AS Total_products,
  MAX(order_date) AS Last_order,
  DATEDIFF(month, Min(order_date), MAX(Order_date)) AS Lifespan
  from base_query
  group by 
  customer_key,
  customer_number,
  customer_name,
  age
  )
  

  select
  customer_key,
  customer_number,
  customer_name,
  age,
  Case when age < 20 then 'Below 20'
  when age between 20 and 29 then '20-29'
  when age between 30 and 39 then '30-39'
  when age between 40 and 49 then '40-49'
  else 'above 50'
  END age_group,
  Case 
  when Lifespan >= 12 and Total_sales > 5000 then 'VIP'
  when lifespan >= 12 and Total_sales <= 5000 then 'regular'
  else 'NEW'
  END AS customer_segments,
  -- compute Recency
  DATEDIFF (MONTH, last_order, getdate()) AS Recency,
  Total_orders,
  Total_sales,
  Total_quantity,
  Total_products,
  Last_order,
  Lifespan,
  --comoute average order value (AVO)
  Total_sales/Total_orders AS avg_order_value,
  --Averag monthly spend
  Case when lifespan = 0 then Total_sales
  else Total_sales/Lifespan
  end Monthly_spend
  from Customer_aggregation

  --Product Report
  -- This report consolidates the key metrics and behaviour
  --Highlights :
  --1. Gather essential feilds such as Product names ,category, subcategory and cost 
  --2. segments customers into categories High performers, Mid-Range and Low-performers
  --3. Aggregate product-level metrics:
  ---Total orders
  ---Total sales
  ---Total quantity sold
  ---Lifespan (in months)
  --4. Calculate valuable KPIs
  ---recency (months since last order)
  ---average order value
  ---average monthly spend

CREATE VIEW dbo.product_report AS
WITH Base_query AS (
    SELECT
        f.order_number,
        f.order_date,
        f.customer_key,
        f.sales_amount,
        f.quantity,
        p.product_key,
        p.product_name,
        p.category,
        p.subcategory,
        p.cost
    FROM fact_sales AS f
    LEFT JOIN dim_products AS p
        ON p.product_key = f.product_key
    WHERE f.order_date IS NOT NULL
),

product_aggregations AS (
    SELECT 
        product_key,
        product_name,
        category,
        subcategory,
        cost,
        COUNT(DISTINCT order_number) AS Total_orders,
        SUM(sales_amount) AS Total_sales,
        SUM(quantity) AS Total_quantity,
        MAX(order_date) AS Last_sale_date,
        DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS Lifespan,
        ROUND(AVG(CAST(sales_amount AS FLOAT) / NULLIF(quantity, 0)), 1) AS Avg_selling_price
    FROM Base_query
    GROUP BY 
        product_key,
        product_name,
        category,
        subcategory,
        cost
)

SELECT 
    product_key,
    product_name,
    category,
    subcategory,
    cost,
    Last_sale_date,
    DATEDIFF(MONTH, Last_sale_date, GETDATE()) AS Recency,
    CASE 
        WHEN Total_sales > 5000 THEN 'High performer'
        WHEN Total_sales >= 1000 THEN 'Mid-Range'
        ELSE 'Low-performer'
    END AS product_segment,
    Lifespan,
    Total_orders,
    Total_sales,
    Total_quantity,
    CAST(Total_sales AS FLOAT) / NULLIF(Total_orders, 0) AS avg_order_revenue,
    CASE 
        WHEN Lifespan = 0 THEN Total_sales
        ELSE Total_sales / Lifespan
    END AS avg_monthly_revenue
FROM product_aggregations;